import { AngularPanel } from "@/components/ui/AngularPanel";
import { StatusIndicator } from "@/components/ui/StatusIndicator";
import { TechnicalLabel } from "@/components/ui/TechnicalLabel";
import type { EditorSnapshot } from "@/lib/schemas";

type PreviewSection = "home" | "about" | "projects" | "project-sections" | "library" | "site-experience" | "experience" | "education" | "certifications" | "skills" | "achievements" | "services" | "social" | "contact";
type RecordValue = Record<string, unknown>;
const collectionLabels: Record<string, string> = { experience: "Experience", education: "Education", certifications: "Certifications", skills: "Skills", achievements: "Achievements", services: "Services" };
const text = (value: unknown) => typeof value === "string" ? value : "";

export function EditorPreview({ content, active, projectFolder }: { content: EditorSnapshot; active: PreviewSection; projectFolder: string }) {
  const sectionLabel = active === "library" ? "Media library" : active === "site-experience" ? "Site experience" : active === "social" ? "Social links" : active[0].toUpperCase() + active.slice(1);
  return <div className="overflow-hidden border border-border bg-background-primary p-6 sm:p-10"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-border pb-6"><div><span className="font-technical text-technical-label uppercase tracking-[0.12em] text-accent">Live draft preview</span><h2 className="mt-2 font-heading text-heading-md uppercase">{sectionLabel}</h2></div><span className="font-technical text-technical-label uppercase text-foreground-muted">Current tab</span></div><div className="pt-8">{active === "home" ? <HomePreview content={content} /> : null}{active === "about" ? <AboutPreview content={content} /> : null}{active === "projects" ? <ProjectPreview content={content} projectFolder={projectFolder} /> : null}{active === "library" ? <LibraryPreview /> : null}{active === "site-experience" ? <SiteExperiencePreview content={content} /> : null}{active === "social" ? <SocialPreview content={content} /> : null}{active === "contact" ? <ContactPreview content={content} /> : null}{["experience", "education", "certifications", "skills", "achievements", "services"].includes(active) ? <CollectionPreview name={active} items={content[active as keyof EditorSnapshot] as unknown as readonly RecordValue[]} /> : null}</div></div>;
}

function SiteExperiencePreview({ content }: { content: EditorSnapshot }) {
  const { cursor, audio } = content.siteExperience;
  return <div className="grid gap-6 sm:grid-cols-2"><div className="border border-border bg-surface p-6"><span className="font-technical text-technical-label uppercase text-accent">Cursor designer</span><p className="mt-3 font-heading text-heading-md uppercase">{cursor.enabled ? cursor.preset : "Disabled"}</p><p className="mt-2 font-body text-body-sm text-foreground-muted">{cursor.scale}× scale · {Math.round(cursor.opacity * 100)}% opacity · {cursor.motionStrength} motion</p><div className="mt-8 flex h-24 items-center justify-center border border-dashed border-border-strong"><span className="h-3 w-3 rounded-full bg-accent shadow-[0_0_28px_var(--accent)]" /><span className="ml-4 h-8 w-8 rounded-full border border-accent/60" /></div></div><div className="border border-border bg-surface p-6"><span className="font-technical text-technical-label uppercase text-accent">Audio engine</span><p className="mt-3 font-heading text-heading-md uppercase">{audio.enabled && !audio.masterMuted ? "Ready" : "Muted"}</p><p className="mt-2 font-body text-body-sm text-foreground-muted">{Object.keys(audio.sounds).length} configured interface sounds · {Math.round(audio.masterVolume * 100)}% master volume</p><div className="mt-8 flex items-end gap-1" aria-hidden="true">{[28, 45, 20, 58, 36, 66, 24, 50].map((height, index) => <span key={index} className="w-2 bg-accent/70" style={{ height }} />)}</div></div></div>;
}

function HomePreview({ content }: { content: EditorSnapshot }) { return <><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div className="min-w-0"><p className="font-technical text-technical-label uppercase tracking-[0.12em] text-accent">{content.site.role}</p><h3 className="mt-3 break-words font-heading text-display-lg uppercase tracking-tight">{content.site.name}</h3><p className="mt-5 max-w-xl font-body text-body-lg text-foreground-muted">{content.site.supportingStatement}</p><p className="mt-3 max-w-xl font-body text-body-md text-foreground-muted">{content.site.introduction}</p></div><AngularPanel className="flex min-h-32 min-w-40 items-end justify-between p-4"><StatusIndicator label={content.site.status} /></AngularPanel></div><div className="mt-8 grid gap-4 border-t border-border pt-6 sm:grid-cols-3"><span className="font-body text-body-sm text-foreground-muted">{content.site.location}</span><span className="font-body text-body-sm text-foreground-muted">{content.site.specialization}</span><span className="font-body text-body-sm text-foreground-muted">{content.projects.filter((project) => project.visible).length} visible projects</span></div></>; }
function AboutPreview({ content }: { content: EditorSnapshot }) { return <div className="grid gap-8"><div><TechnicalLabel accent as="div">{content.about.headline}</TechnicalLabel><div className="mt-5 grid gap-4 font-body text-body-lg text-foreground-muted">{content.about.philosophy.map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div></div><div className="grid gap-3 sm:grid-cols-2">{content.about.principles.map((principle) => <AngularPanel key={principle.title} className="p-5"><h3 className="font-heading text-heading-sm uppercase">{principle.title}</h3><p className="mt-2 font-body text-body-sm text-foreground-muted">{principle.description}</p></AngularPanel>)}</div></div>; }
function ProjectPreview({ content, projectFolder }: { content: EditorSnapshot; projectFolder: string }) { const project = content.projects.find((item) => item.folderName === projectFolder) ?? content.projects[0]; if (!project) return <Empty text="No project selected." />; return <div className="grid gap-8"><div><TechnicalLabel accent as="div">{project.status} / {project.year}</TechnicalLabel><h3 className="mt-3 break-words font-heading text-display-md uppercase">{project.name}</h3><p className="mt-3 font-body text-body-lg text-foreground-muted">{project.tagline}</p><p className="mt-5 max-w-2xl font-body text-body-md text-foreground-muted">{project.description}</p></div><div className="grid gap-4 border-y border-border py-5 sm:grid-cols-3"><Meta label="Category" value={project.category.join(" / ")} /><Meta label="Role" value={project.role.join(" / ")} /><Meta label="Tech" value={project.technologies.join(" / ")} /></div><div className="grid gap-3 sm:grid-cols-2">{project.features.slice(0, 4).map((feature) => <AngularPanel key={feature.title} className="p-5"><h4 className="font-heading text-heading-sm uppercase">{feature.title}</h4><p className="mt-2 font-body text-body-sm text-foreground-muted">{feature.description}</p></AngularPanel>)}</div>{project.caseStudy.overview ? <div><TechnicalLabel accent as="div">Case study overview</TechnicalLabel><p className="mt-3 max-w-2xl whitespace-pre-wrap font-body text-body-md text-foreground-muted">{project.caseStudy.overview}</p></div> : null}</div>; }
function CollectionPreview({ name, items }: { name: string; items: readonly RecordValue[] }) { return <div><div className="mb-5 flex items-center justify-between"><TechnicalLabel accent as="div">{collectionLabels[name]}</TechnicalLabel><span className="font-technical text-technical-label uppercase text-foreground-muted">{items.filter((item) => item.visible !== false).length} visible</span></div><div className="grid gap-3 sm:grid-cols-2">{items.map((item, index) => <AngularPanel key={String(item.id ?? index)} className="p-5"><TechnicalLabel>{text(item.date) || text(item.startDate) || `Entry ${String(index + 1).padStart(2, "0")}`}</TechnicalLabel><h3 className="mt-2 font-heading text-heading-sm uppercase">{text(item.title) || text(item.position) || text(item.program) || text(item.category) || text(item.company) || "Untitled entry"}</h3><p className="mt-2 whitespace-pre-wrap font-body text-body-sm text-foreground-muted">{text(item.description) || text(item.issuer) || text(item.institution) || text(item.organization) || text(item.location)}</p></AngularPanel>)}</div></div>; }
function SocialPreview({ content }: { content: EditorSnapshot }) { return <div className="grid gap-3 sm:max-w-2xl">{content.socialLinks.filter((link) => link.visible !== false).map((link) => <div key={link.label} className="flex items-center justify-between border-b border-border py-4"><span className="font-heading text-heading-sm uppercase">{link.label}</span><span className="break-all font-body text-body-sm text-foreground-muted">{link.href}</span></div>)}</div>; }
function ContactPreview({ content }: { content: EditorSnapshot }) { return <div className="grid gap-4 sm:max-w-2xl"><TechnicalLabel accent as="div">Contact</TechnicalLabel><h3 className="font-heading text-display-md uppercase">{content.contact.heading}</h3><p className="font-body text-body-lg text-foreground-muted">{content.contact.introduction}</p><button type="button" className="w-fit bg-accent px-4 py-3 font-technical text-technical-label uppercase text-accent-foreground">{content.contact.submitLabel}</button></div>; }
function LibraryPreview() { return <Empty text="Media library assets are available in the Media Library tab. Uploads and reusable files are managed there." />; }
function Meta({ label, value }: { label: string; value: string }) { return <div><TechnicalLabel>{label}</TechnicalLabel><p className="mt-2 font-body text-body-sm text-foreground-muted">{value || "—"}</p></div>; }
function Empty({ text: value }: { text: string }) { return <p className="border border-dashed border-border-strong p-8 font-body text-body-md text-foreground-muted">{value}</p>; }
